name: 发布 Release v2

on:
  push:
    tags:
      - v*.*.*
  # push:
  # branches: master

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          files: |
            tailwind.config.ts
